services:
  order-postgres:
    image: postgres:15
    container_name: order-postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${ORDER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ORDER_POSTGRES_PASSWORD}
      POSTGRES_DB: ${ORDER_POSTGRES_DB}
    ports:
      - "${ORDER_POSTGRES_PORT}:5432"
    volumes:
      - order-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${ORDER_POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - rocket-shop-network

  order-service:
    build:
      context: ../../../
      dockerfile: deploy/docker/order/Dockerfile
    container_name: order-service
    env_file:
      - .env
    environment:
      - ORDER_POSTGRES_DSN=postgres://${ORDER_POSTGRES_USER}:${ORDER_POSTGRES_PASSWORD}@order-postgres:5432/${ORDER_POSTGRES_DB}?sslmode=disable
      - ORDER_HTTP_ADDRESS=:8080
      - KAFKA_BROKERS=kafka:9092
      - ORDER_PAID_PRODUCER_TOPIC=${ORDER_PAID_PRODUCER_TOPIC:-order.paid}
      - ORDER_ASSEMBLED_CONSUMER_TOPIC=${ORDER_ASSEMBLED_CONSUMER_TOPIC:-ship.assembled}
      - ORDER_ASSEMBLED_CONSUMER_GROUP_ID=${ORDER_ASSEMBLED_CONSUMER_GROUP_ID:-order-consumer-group}
    ports:
      - "8082:8080"
    depends_on:
      order-postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - rocket-shop-network

networks:
  rocket-shop-network:
    external: true

volumes:
  order-pgdata:
