services:
  inventory-mongodb:
    image: ${INVENTORY_MONGO_IMAGE}
    container_name: inventory-mongodb
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${INVENTORY_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${INVENTORY_MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${INVENTORY_MONGO_DB}
    ports:
      - "${INVENTORY_MONGO_PORT}:27017"
    volumes:
      - inventory-mongodata:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - rocket-shop-network

  inventory-service:
    build:
      context: ../../../
      dockerfile: deploy/docker/inventory/Dockerfile
    container_name: inventory-service
    env_file:
      - .env
    environment:
      - INVENTORY_MONGO_URI=mongodb://${INVENTORY_MONGO_USER}:${INVENTORY_MONGO_PASSWORD}@inventory-mongodb:27017
      - INVENTORY_MONGO_DB=${INVENTORY_MONGO_DB}
      - INVENTORY_GRPC_ADDRESS=:50051
    ports:
      - "50051:50051"
    depends_on:
      inventory-mongodb:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - rocket-shop-network

networks:
  rocket-shop-network:
    external: true

volumes:
  inventory-mongodata:
